import { NextRequest, NextResponse } from "next/server";
import { Octokit } from "@octokit/rest";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface SlackMessage {
  user: string;
  text: string;
  ts: string;
}

interface TriageRequestBody {
  thread: SlackMessage[];
}

// ---------------------------------------------------------------------------
// GitHub helper
// ---------------------------------------------------------------------------

/**
 * Returns an authenticated Octokit instance using the Personal Access Token
 * stored in the GITHUB_PAT environment variable.
 */
function getOctokit(): Octokit {
  const token = process.env.GITHUB_PAT;
  if (!token) {
    throw new Error(
      "GITHUB_PAT is not set. Add it to your .env.local file."
    );
  }
  return new Octokit({ auth: token });
}

// ---------------------------------------------------------------------------
// POST /api/triage
// ---------------------------------------------------------------------------

export async function POST(req: NextRequest): Promise<NextResponse> {
  let body: TriageRequestBody;

  try {
    body = (await req.json()) as TriageRequestBody;
  } catch {
    return NextResponse.json(
      { ok: false, error: "Invalid JSON body." },
      { status: 400 }
    );
  }

  if (!Array.isArray(body?.thread) || body.thread.length === 0) {
    return NextResponse.json(
      { ok: false, error: "Request body must contain a non-empty `thread` array." },
      { status: 422 }
    );
  }

  const owner = process.env.GITHUB_OWNER ?? "TeyYongZhun";
  const repo = process.env.GITHUB_REPO ?? "ChatToPR_sandbox";
  const targetFile = "sample.txt";
  const commitMessage = "fix: apply triage patch from ChatToPR";
  const replacementCode = body.thread.map((m) => m.text).join("\n");

  try {
    const octokit = getOctokit();

    // 1. Resolve the default branch SHA to base the new branch on.
    const { data: repoData } = await octokit.repos.get({ owner, repo });
    const defaultBranch = repoData.default_branch;

    const { data: refData } = await octokit.git.getRef({
      owner,
      repo,
      ref: `heads/${defaultBranch}`,
    });
    const baseSha = refData.object.sha;

    // 2. Create a uniquely named branch.
    const branchName = `triage/${Date.now()}`;
    await octokit.git.createRef({
      owner,
      repo,
      ref: `refs/heads/${branchName}`,
      sha: baseSha,
    });

    // 3. Retrieve the current blob SHA of the target file (required by the
    //    contents API to update an existing file; ignored for new files).
    let fileSha: string | undefined;
    try {
      const { data: fileData } = await octokit.repos.getContent({
        owner,
        repo,
        path: targetFile,
        ref: defaultBranch,
      });
      if (!Array.isArray(fileData) && fileData.type === "file") {
        fileSha = fileData.sha;
      }
    } catch {
      // File does not exist yet — createOrUpdateFileContents will create it.
    }

    // 4. Commit the replacement content to the new branch.
    await octokit.repos.createOrUpdateFileContents({
      owner,
      repo,
      path: targetFile,
      message: commitMessage,
      content: Buffer.from(replacementCode).toString("base64"),
      branch: branchName,
      ...(fileSha ? { sha: fileSha } : {}),
    });

    // 5. Open a Pull Request.
    const { data: pr } = await octokit.pulls.create({
      owner,
      repo,
      title: commitMessage,
      head: branchName,
      base: defaultBranch,
      body: "Automated triage patch generated by ChatToPR.",
    });

    return NextResponse.json({ ok: true, prUrl: pr.html_url }, { status: 200 });
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    return NextResponse.json(
      { ok: false, error: message },
      { status: 500 }
    );
  }
}
