import { NextRequest, NextResponse } from "next/server";
import { Octokit } from "@octokit/rest";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface SlackMessage {
  user: string;
  text: string;
  ts: string;
}

interface TriageRequestBody {
  thread: SlackMessage[];
}

// ---------------------------------------------------------------------------
// Incident record builder
// ---------------------------------------------------------------------------

/**
 * Extracts unique, sorted participants from the thread.
 */
function extractParticipants(thread: SlackMessage[]): string[] {
  return Array.from(new Set(thread.map((m) => m.user)));
}

/**
 * Extracts ticket/PR references like #4821 or #312 from all messages.
 */
function extractRefs(thread: SlackMessage[]): string[] {
  const found = new Set<string>();
  const re = /#(\d+)/g;
  for (const m of thread) {
    let match: RegExpExecArray | null;
    re.lastIndex = 0;
    while ((match = re.exec(m.text)) !== null) {
      found.add(`#${match[1]}`);
    }
  }
  return Array.from(found);
}

/**
 * Extracts inline code references (backtick-quoted tokens) from all messages.
 */
function extractCodeRefs(thread: SlackMessage[]): string[] {
  const found = new Set<string>();
  const re = /`([^`]+)`/g;
  for (const m of thread) {
    let match: RegExpExecArray | null;
    re.lastIndex = 0;
    while ((match = re.exec(m.text)) !== null) {
      found.add(match[1]);
    }
  }
  return Array.from(found);
}

/**
 * Heuristically identifies the root-cause, fix, and rollback messages.
 * Looks for key phrases; falls back to undefined if none match.
 */
function classifyMessages(thread: SlackMessage[]): {
  rootCause: SlackMessage | undefined;
  fix: SlackMessage | undefined;
  rollback: SlackMessage | undefined;
} {
  const rootCauseKeywords = /root cause|root-cause|caused by|reason:/i;
  const fixKeywords = /fix|hotfix|patch|swap|streaming|async iterator/i;
  const rollbackKeywords = /rolling back|roll back|revert/i;

  return {
    rootCause: thread.find((m) => rootCauseKeywords.test(m.text)),
    fix: thread.find((m) => fixKeywords.test(m.text) && !rollbackKeywords.test(m.text)),
    rollback: thread.find((m) => rollbackKeywords.test(m.text)),
  };
}

/**
 * Builds the full incident Markdown document from the thread.
 */
function buildIncidentRecord(incidentId: string, thread: SlackMessage[]): string {
  const participants = extractParticipants(thread);
  const refs = extractRefs(thread);
  const codeRefs = extractCodeRefs(thread);
  const { rootCause, fix, rollback } = classifyMessages(thread);

  const now = new Date().toISOString();

  // ── Summary table ──────────────────────────────────────────────────────────
  const summaryTable = [
    `| Field | Value |`,
    `|---|---|`,
    `| **Incident ID** | INC-${incidentId} |`,
    `| **Created** | ${now} |`,
    `| **Participants** | ${participants.join(", ")} |`,
    `| **Ticket / PR refs** | ${refs.length ? refs.join(", ") : "—"} |`,
    `| **Code refs** | ${codeRefs.length ? codeRefs.map((c) => `\`${c}\``).join(", ") : "—"} |`,
  ].join("\n");

  // ── Highlighted signals ────────────────────────────────────────────────────
  function highlightBlock(label: string, msg: SlackMessage | undefined): string {
    if (!msg) return `### ${label}\n\n_Not identified in thread._\n`;
    return [
      `### ${label}`,
      ``,
      `> **${msg.user}** · ${msg.ts}`,
      `>`,
      `> ${msg.text}`,
      ``,
    ].join("\n");
  }

  // ── Full timeline ──────────────────────────────────────────────────────────
  const timelineRows = thread.map((m) => `| ${m.ts} | **${m.user}** | ${m.text} |`);
  const timeline = [
    `| Time | Author | Message |`,
    `|---|---|---|`,
    ...timelineRows,
  ].join("\n");

  // ── Assemble document ──────────────────────────────────────────────────────
  return [
    `# Incident Report — INC-${incidentId}`,
    ``,
    `> Auto-generated by ChatToPR on ${now}`,
    ``,
    `---`,
    ``,
    `## Summary`,
    ``,
    summaryTable,
    ``,
    `---`,
    ``,
    `## Root Cause`,
    ``,
    highlightBlock("Root Cause", rootCause),
    `---`,
    ``,
    `## Fix`,
    ``,
    highlightBlock("Fix", fix),
    `---`,
    ``,
    `## Rollback`,
    ``,
    highlightBlock("Rollback", rollback),
    `---`,
    ``,
    `## Full Timeline`,
    ``,
    timeline,
    ``,
  ].join("\n");
}

// ---------------------------------------------------------------------------
// GitHub helper
// ---------------------------------------------------------------------------

/**
 * Returns an authenticated Octokit instance using the Personal Access Token
 * stored in the GITHUB_PAT environment variable.
 */
function getOctokit(): Octokit {
  const token = process.env.GITHUB_PAT;
  if (!token) {
    throw new Error(
      "GITHUB_PAT is not set. Add it to your .env.local file."
    );
  }
  return new Octokit({ auth: token });
}

// ---------------------------------------------------------------------------
// POST /api/triage
// ---------------------------------------------------------------------------

export async function POST(req: NextRequest): Promise<NextResponse> {
  let body: TriageRequestBody;

  try {
    body = (await req.json()) as TriageRequestBody;
  } catch {
    return NextResponse.json(
      { ok: false, error: "Invalid JSON body." },
      { status: 400 }
    );
  }

  if (!Array.isArray(body?.thread) || body.thread.length === 0) {
    return NextResponse.json(
      { ok: false, error: "Request body must contain a non-empty `thread` array." },
      { status: 422 }
    );
  }

  // Derive a short numeric incident ID from the current timestamp.
  const incidentId = Date.now().toString().slice(-6);

  const owner = process.env.GITHUB_OWNER ?? "TeyYongZhun";
  const repo = process.env.GITHUB_REPO ?? "ChatToPR_sandbox";
  const targetFile = `triage/INC-${incidentId}.md`;
  const commitMessage = `incident: add INC-${incidentId} triage record`;
  const incidentRecord = buildIncidentRecord(incidentId, body.thread);

  try {
    const octokit = getOctokit();

    // 1. Resolve the default branch SHA to base the new branch on.
    const { data: repoData } = await octokit.repos.get({ owner, repo });
    const defaultBranch = repoData.default_branch;

    const { data: refData } = await octokit.git.getRef({
      owner,
      repo,
      ref: `heads/${defaultBranch}`,
    });
    const baseSha = refData.object.sha;

    // 2. Create a uniquely named branch.
    const branchName = `triage/INC-${incidentId}`;
    await octokit.git.createRef({
      owner,
      repo,
      ref: `refs/heads/${branchName}`,
      sha: baseSha,
    });

    // 3. Retrieve the current blob SHA of the target file (required by the
    //    contents API to update an existing file; ignored for new files).
    let fileSha: string | undefined;
    try {
      const { data: fileData } = await octokit.repos.getContent({
        owner,
        repo,
        path: targetFile,
        ref: defaultBranch,
      });
      if (!Array.isArray(fileData) && fileData.type === "file") {
        fileSha = fileData.sha;
      }
    } catch {
      // File does not exist yet — createOrUpdateFileContents will create it.
    }

    // 4. Commit the incident record to the new branch.
    await octokit.repos.createOrUpdateFileContents({
      owner,
      repo,
      path: targetFile,
      message: commitMessage,
      content: Buffer.from(incidentRecord).toString("base64"),
      branch: branchName,
      ...(fileSha ? { sha: fileSha } : {}),
    });

    // 5. Open a Pull Request.
    const { data: pr } = await octokit.pulls.create({
      owner,
      repo,
      title: commitMessage,
      head: branchName,
      base: defaultBranch,
      body: [
        `## Incident INC-${incidentId}`,
        ``,
        `Auto-generated triage record from a ChatToPR Slack thread.`,
        ``,
        `**File committed:** \`${targetFile}\``,
      ].join("\n"),
    });

    return NextResponse.json({ ok: true, prUrl: pr.html_url }, { status: 200 });
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    return NextResponse.json(
      { ok: false, error: message },
      { status: 500 }
    );
  }
}
